### ISSUE TITLE
Images / Description of Pattern?

### ISSUE THREAD

**Issue by Zevgor** [Ugric/WayStones#9]
Hello, I was trying to implement Waystones on my server and realized that the image links in both the spigot.mc listing as well as this GitHub page are gone. Because of this, I can not figure out how to construct the waystone.
Can you re-upload or describe the build?

**Comment by Ugric** [comment]
Hi. I'm not sure why the images have disappeared.

This is an image of the waystone:

![image](https://github.com/user-attachments/assets/5a832017-71c7-4f06-8a9b-d12c30a91a0a)

There is also instructions on how to build it in the read me of the GitHub repo:

1. Start by creating a 3 by 3 base made out of crying obsidian. 
2. Then place 4 Deepslate Brick Slabs like so. 
3. Place a Lodestone in the middle of the slabs. 
4. Place a Deepslate Brick Wall on top of the Lodestone. 
5. Then place another Lodestone on top of the wall. 
6. Finally, right-click the wall with an End Crystal and feel the power of the WayStone :D

Thanks for using the plugin but I've not been developing it recently, so it might work on 1.21 but I haven't tested it.

I stupidly developed it on a paper server so there may be issues with running it on spigot, I haven't tested it. If you find any issues, feel free to create an issue or fork the project and fix it and create a pull request.

**Comment by Ugric** [comment]
oh the images have disappeared because i was using discord to host them 🤦‍♂️. ill try find them and reupload them.

**Comment by Ugric** [comment]
![image](https://github.com/user-attachments/assets/5ba0a9a2-8d4b-4ddc-b7bb-499f1db3bc14)
![image](https://github.com/user-attachments/assets/686ba115-9404-415a-a52c-6ebd2d4ae6e1)
![image](https://github.com/user-attachments/assets/92cb9500-bc08-4966-8e0b-c51c89f17da9)
![image](https://github.com/user-attachments/assets/9893e992-b77e-4877-a169-a844e135d53b)
![image](https://github.com/user-attachments/assets/f110003d-ed49-4a60-915c-6217fc3adb45)
![image](https://github.com/user-attachments/assets/c94ed171-32ae-4205-88a0-2538d696ec2d)
![image](https://github.com/user-attachments/assets/6932c452-bf54-41a9-9cd7-17e5dfdef400)

**Comment by Zevgor** [comment]
Thank you! It does work on 1.21, I tested it on my server yesterday. Great plugin!

**Comment by Ugric** [comment]
ah thank you, glad you enjoy it :)
